# Generated by Django 5.1.1 on 2024-09-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_property_owner_alter_property_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='properties', to='rentapp.propertyimage'),
        ),
    ]
